apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.rollout-app: |
    url: 'http://el-rollout-app-el.notifications-demo.svc:8080'

  template.rollout-app: |
    webhook:
      rollout-app:
        method: POST
        path: /
        body: |
        {
          {{if eq .app.status.operationState.phase "Running"}} "state": "pending"{{end}}
          {{if eq .app.status.operationState.phase "Succeeded"}} "state": "success"{{end}}
          {{if eq .app.status.operationState.phase "Error"}} "state": "error"{{end}}
          {{if eq .app.status.operationState.phase "Failed"}} "state": "error"{{end}},
          "description": "ArgoCD Notification",
          "application": "{{.app.metadata.name}}"
        }