apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.rollout-app: |-
    url: https://webhook.site/01170e28-5e04-456e-a7b8-e36306831c7d
  template.rollout-app-sync: |-
    webhook:
      rollout-app:
        method: POST
        path: /
        body: |
          {"state": "success"}