apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rollout-app
spec:
  params:
  - name: deployment
    description: Deployment name.
    default: petclinic
    type: string
  tasks:
  - name: openshift-client
    params:
    - name: SCRIPT
      value: oc rollout restart deployment $(params.deployment)
    - name: VERSION
      value: latest
    taskRef:
      kind: ClusterTask
      name: openshift-client
