apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: rollout-app-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: rollout-app-binding
  template:
    ref: rollout-app-template