apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notifications-demo

resources:
  - ../../base

images:
  - name: petclinic
    newName: quay.io/pittar/petclinic
    newTag: dev
